{% set name = "girder" %}
{% set version = "3.2.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22d1dd4d5741328036c3032d2aa609f6a735343950437bf24aefaef72c92e2af

build:
  entry_points:
    - girder-server = girder.cli.serve:main
    - girder = girder.cli:main
    - girder-sftpd = girder.cli.sftpd:main
    - girder-shell = girder.cli.shell:main
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python >={{ python_min }}
    - boto3
    - botocore
    - cherrypy
    - click
    - click-plugins
    - dogpile.cache
    - filelock
    - jsonschema
    - mako
    - paramiko
    - passlib
    - pymongo >=4
    - pyyaml
    - psutil
    - pyopenssl
    - python-dateutil
    - pytz
    - requests

test:
  imports:
    - girder
    - girder.api
    - girder.api.v1
    - girder.models
    - girder.utility

  commands:
    - girder-server --help
    - girder --help
    - girder-sftpd --help
    - girder-shell --help
    - pip check

  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/girder/girder
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Web-based data management platform
  dev_url: https://github.com/girder/girder
  doc_url: https://girder.readthedocs.org

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
