{% set name = "girder" %}
{% set version = "3.1.15" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 763c73c5c89e343cb33307fdbe3da1d0ec28f534b6128ae9f32d3f5343d8ef4a

build:
  entry_points:
    - girder-server = girder.cli.serve:main
    - girder = girder.cli:main
    - girder-sftpd = girder.cli.sftpd:main
    - girder-shell = girder.cli.shell:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm

  run:
    - python >=3.6
    - bcrypt
    - boto3
    - cherrypy <11.1
    - click >=7.0,<8.0
    - filelock
    - jsonschema
    - mako
    - pymongo
    - pyyaml
    - requests
    - psutil
    - python-dateutil
    - pytz
    - six >=1.9
    - celery >=4.0.0
    - pydicom
    - geojson
    - ctk-cli
    - pillow
    - numpy
    - paramiko
    - passlib
    - pip
    - dogpile.cache

test:
  imports:
    - girder
    - girder.api
    - girder.api.v1
    - girder.models
    - girder.utility

  commands:
    - girder-server --help
    - girder --help
    - girder-sftpd --help
    - girder-shell --help
    - pip check

  requires:
    - pip

about:
  home: https://github.com/girder/girder
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Web-based data management platform
  dev_url: https://github.com/girder/girder
  doc_url: https://girder.readthedocs.org

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
