{% set name = "girder" %}
{% set version = "3.0.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "8ac38d291be341b7851794d10d65c3b9be6cd61702a10506deddabad7066640a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  entry_points:
    - girder-server = girder.__main__:main
    - girder-install = girder.utility.install:main
    - girder-sftpd = girder.api.sftp:_main
    - girder-shell = girder.utility.shell:main

  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - bcrypt
    - boto3
    - cherrypy
    - click
    - filelock
    - jsonschema
    - mako
    - pymongo
    - pyyaml
    - requests
    - psutil
    - python-dateutil
    - pytz
    - six >=1.9
    - celery >=4.0.0
    - pydicom
    - geojson
    - ctk-cli
    - pillow
    - numpy
    - shutilwhich  # [py2k]
    - snakebite  # [py2k]
    - hachoir-core  # [py2k]
    - hachoir-metadata  # [py2k]
    - hachoir-parser  # [py2k]
    - paramiko
    - pip

test:
  imports:
    - girder
    - girder.api
    - girder.api.v1
    - girder.external
    - girder.models
    - girder.utility

  commands:
    - girder-server --help
    - girder-install --help

about:
  home: https://github.com/girder/girder
  license: Apache 2.0
  license_file: LICENSE
  license_family: Apache
  summary: Web-based data management platform
  dev_url: https://github.com/girder/girder
  doc_url: https://girder.readthedocs.org

extra:
  recipe-maintainers:
    - pmlandwehr
