{% set name = "girder" %}
{% set version = "3.0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ac38d291be341b7851794d10d65c3b9be6cd61702a10506deddabad7066640a

build:
  entry_points:
    - girder-server = girder.__main__:main
    - girder-install = girder.utility.install:main
    - girder-sftpd = girder.api.sftp:_main
    - girder-shell = girder.utility.shell:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - bcrypt
    - boto3
    - cherrypy
    - click
    - filelock
    - jsonschema
    - mako
    - pymongo
    - pyyaml
    - requests
    - psutil
    - python-dateutil
    - pytz
    - six >=1.9
    - celery >=4.0.0
    - pydicom
    - geojson
    - ctk-cli
    - pillow
    - numpy
    - paramiko
    - pip

test:
  imports:
    - girder
    - girder.api
    - girder.api.v1
    - girder.external
    - girder.models
    - girder.utility

  commands:
    - girder-server --help
    - girder-install --help
    - pip check
  
  requires:
    - pip

about:
  home: https://github.com/girder/girder
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Web-based data management platform
  dev_url: https://github.com/girder/girder
  doc_url: https://girder.readthedocs.org

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
