{% set name = "girder" %}
{% set version = "2.4.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "447c46bafeca5a8713df17a4165b9122c4e6d3309625107296dbb9bacd3df150" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  entry_points:
    - girder-server = girder.__main__:main
    - girder-install = girder.utility.install:main
    - girder-sftpd = girder.api.sftp:_main
    - girder-shell = girder.utility.shell:main

  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - bcrypt
    - boto3
    - cherrypy <11.1
    - click
    - filelock
    - funcsigs  # [py<35]
    - jsonschema
    - mako
    - pymongo >=3.5
    - pyyaml
    - psutil
    - python-dateutil
    - pytz
    - requests
    - shutilwhich  # [py<33]
    - six >=1.9
    - pydicom
    - geojson
    - ctk-cli
    - pyldap
    - pillow
    - numpy
    - celery >=4
    - snakebite  # [py2k]
    - hachoir-core  # [py2k]
    - hachoir-metadata  # [py2k]
    - hachoir-parser  # [py2k]
    - paramiko
    - pip

test:
  imports:
    - girder
    - girder.api
    - girder.api.v1
    - girder.conf
    - girder.external
    - girder.mail_templates
    - girder.models
    - girder.utility

  commands:
    - girder-server --help
    - girder-install --help
    - girder-sftpd --help
    - girder-shell --help

about:
  home: https://github.com/girder/girder
  license: Apache 2.0
  license_file: LICENSE
  license_family: Apache
  summary: Web-based data management platform
  dev_url: https://github.com/girder/girder
  doc_url: https://girder.readthedocs.org

extra:
  recipe-maintainers:
    - pmlandwehr
