{% set name = "girder" %}
{% set version = "2.5.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "d155bb5a012045d1f3cc430d2295cfb5051e6009298934791154b52ba63f2e36" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  entry_points:
    - girder-server = girder.cli.serve:main
    - girder-install = girder.utility.install:main
    - girder-sftpd = girder.cli.sftpd:main
    - girder-shell = girder.cli.shell:main
    - girder = girder.cli:main
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - bcrypt
    - boto3
    - cherrypy <11.1
    - click
    - click-plugins
    - dogpile.cache
    - filelock
    - funcsigs  # [py2k]
    - jsonschema
    - mako
    - pymongo >=3.5
    - pyyaml
    - psutil
    - python-dateutil <2.7
    - pytz
    - requests
    - shutilwhich  # [py2k]
    - six >=1.9
    
    # plugin requireiments
    - celery >=4
    - pydicom >=1.0.2
    - fusepy >=2.0.4
    - geojson
    - snakebite  # [py2k]
    - ctk-cli
    - girder-worker-utils >=0.7.2
    - girder-worker >=0.4.0
    - pyldap
    - hachoir-core  # [py2k]
    - hachoir-metadata  # [py2k]
    - hachoir-parser  # [py2k]
    - pillow
    - numpy
    
    # extra requirements
    - paramiko
    - pip

test:
  imports:
    - girder
    - girder.api
    - girder.api.v1
    - girder.external
    - girder.models
    - girder.utility

  commands:
    - girder-server --help
    - girder-install --help
    - girder-sftpd --help
    - girder-shel --help
    - girder --help

about:
  home: https://github.com/girder/girder
  license: Apache 2.0
  license_file: LICENSE
  license_family: Apache
  summary: Web-based data management platform
  dev_url: https://github.com/girder/girder
  doc_url: https://girder.readthedocs.org

extra:
  recipe-maintainers:
    - pmlandwehr
