{%set name = "girder" %}
{%set version = "2.0.0" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "e23f6ae1a28dc93585aabe6312367376e53615687911e73ec8005a858e95cef1" %}
{%set build_num = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  entry_points:
    - girder-server = girder.__main__:main
    - girder-install = girder.utility.install:main

  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - bcrypt
    - boto
    - cherrypy <8
    - mako
    - pymongo >=3
    - pyyaml
    - requests
    - psutil
    - python-dateutil
    - pytz
    - six >=1.9
    - celery
    - geojson
    - pillow
    - pydicom
    - numpy
    - pyjwt
    - cryptography
    - shutilwhich  # [py<33]
    - snakebite  # [not py3k]
    - hachoir-core  # [not py3k]
    - hachoir-metadata  # [not py3k]
    - hachoir-parser  # [not py3k]
    - paramiko
    - pip

test:
  imports:
    - girder
    - girder.api
    - girder.api.v1
    - girder.external
    - girder.models
    - girder.utility

  commands:
    - girder-server --help
    - girder-install --help

about:
  home: https://github.com/girder/girder
  license: Apache 2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Web-based data management platform'
  dev_url: https://github.com/girder/girder
  doc_url: https://girder.readthedocs.org

extra:
  recipe-maintainers:
    - pmlandwehr
