schema_version: 1

context:
  name: girder
  version: "5.0.18"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 7f984c5a05ef48a9659eb164075af29e9db0124589a5be277a94e6b7e0fc49b1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - girder-server = girder.cli.serve:main
      - girder = girder.cli:main
      - girder-sftpd = girder.cli.sftpd:main
      - girder-shell = girder.cli.shell:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python >=${{ python_min }}
    - boto3
    - botocore
    - cherrypy
    - cheroot <11
    - click
    - click-plugins
    - dogpile.cache
    - filelock
    - jsonschema
    - mako
    - packaging
    - paramiko
    - passlib
    - pymongo >=4
    - pyyaml
    - psutil
    - pyopenssl
    - python-dateutil
    - pytz
    - requests
    - pyotp
    - uvicorn
    - redis-py
    - starlette
    - websockets
    - girder-worker

tests:
  - python:
      imports:
        - girder
        - girder.api
        - girder.api.v1
        - girder.models
        - girder.utility
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - girder-server --help
      - girder --help
      - girder-sftpd --help
      - girder-shell --help

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Web-based data management platform
  homepage: https://github.com/girder/girder
  repository: https://github.com/girder/girder
  documentation: https://girder.readthedocs.org

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
