travis:
  secure:
    BINSTAR_TOKEN: O/iiNl7sx3XdNBRT4kLyyGPjaJZhlWX8PC5RR0DfUKuBUyRSgVQbuHKWzDnlaZNUAeYPMegvxDgFpgBYxF5/yTvLwlzuN0RKLqkEYL1UZ0Mocw7ePNV9QRHVOpzOJhOjrHDAWU9tDVmyp8mfWZ7BhIT0HImUmmy08x5W2z5bCFo8rMuRtSYkFgq68QKoPS1HhxsLKaqP6SU0xzXt5bw02pqkEhEsxAsGxcGgOZVf2RkReJDGiO4TAO6vm1ak2cBO67Fe98sbLLO9sPxZtZpaq/ijOhIeO4mHVZb+GoAhzH15EhdMcKXv8+QZ5H2pPmcsaqzo+3WwJ8eG7Ecs36H1ekucwg3iLcAUPsg9Y54axE5y2xM7As9nh6/erjHJ12hg1UYAmhf80mGiEjRZSsEtqUKyycO7UKl7Rw6jAO7C40bJhHZZSmB4oMhoEZVjBazgMuUA1uYclfnsA/7PVCH0n64Badt92T3Y9EAtsjt9J88dxO2QbJUzXtOJ3XzaSyk5f8ne1cNC5g6XKbWS/esrtrx92faUm0pNMYKLcDmIhtjEaCbRWO84y1Iip2aJRHBA/jhfEJ5AObUEr1jcZrDbb3RdDJTE9lqeeKxKsxvNvGb5nXS7Jtvue2KTgkFMVsrcvo8RVtLaf677N8ONzlJJ5GoSZGgUWM16AfZqbnoe+fA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
