travis:
  secure:
    BINSTAR_TOKEN: gc5FG1Ii4OEamFlx+VlVZ2E5lWa0KcWjIJFrpIvcLXiUUpVpId4z9F0DgbJnwpBAj1niFNeJ5IwnUGMi8H6KhO4LXZ9qVeQ8v1T+cY4hOZvdCkYMKfHtzRj5DemKGu662zVnfx7eyb6yOWhQb4tT/6P1AJtRhvbpMSo63X9jqkGn6t/mrjxFOLpePZ2GAZtfH1Tkk9ogWp7FeKaaXjN29Ad3WKdJt414zQMB6HqjipSQrbk5WZn6Ieb1tXafnq90cp3lir8KmGqAFG1FIhx9V1arNeomgCeiSsn0yKioryJo5NCeEzooboAWkPIsTeP+ejxEcaCV6tgJuMNdsWRBD2vXmaLnXYtLZ0EjfgJRfwXjCYXdECT1JkAS41c5fbHmcXqEeKrqq532y/xML7m9fnE7pbqcQrTRSLOrTVw0XcwmycOFt8atb22LzP9RaTY3s3YmXGH5xBG9fomIVytVlte0wJVKHFc2SQrlxpvKMrl40OtJPgHfNo/BH5W5tovxJOnAPyEcaDBwNDmWTXyYKFrbcloHao76XPYrgRGaH18pMqW8zEL9tNkImcRQLB5v+27FjgBoYos61/PpVE5+ZVu09JjK6suDABqlBSXsb69Kqfjj6bKM3UJ1zYgwMbJwoBLmMz8b66TON1vZDyUUlv5gNHe9kAKLc0LnXwGdiZw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
